### ISSUE TITLE
Update MIOpen to current version (2.3.0 or 2.4.0)?

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/RadeonML#1]
Hi,

I'm just seeing both binary MIOpen libraries on Windows and Linux have version 2.0.1..
seeing MIOpen site on github seems current version is 2.3.0:
https://github.com/ROCmSoftwarePlatform/MIOpen/releases/tag/2.3.0
even found traces of 2.4 version coming soon:
https://github.com/ROCmSoftwarePlatform/MIOpen/commit/2364745ceb790f5d0b3919fe8d67232f3f645187

just curious why not using latest release, as 2.0.1 seems 9 month old by now:
https://github.com/ROCmSoftwarePlatform/MIOpen/releases/tag/2.0.1

thanks..

**Comment by BenjaminCoquelle** [comment]
Hi 
We can only use the OpenCL backend for MIOpen as we target the amdgpu stack or old windows platform and not much as changed here for the past months.
MIopen main target is HIP and targets ROCm only. If you want to use inference on a ROCm system you can use MIGraphX. It will use the latest from MIopen and HIP
https://github.com/ROCmSoftwarePlatform/AMDMIGraphX

**Comment by oscarbg** [comment]
thanks for comments.. make sense..
