### ISSUE TITLE
TF model format for LoadModel?

### ISSUE THREAD

**Issue by camilltrueeb** [GPUOpen-LibrariesAndSDKs/RadeonML#10]
According to documentation, models can be loaded in both the ONNX and TF format using    

```
// Load model
rml::Model model = context.LoadModel(model_path);
```

Currently I am working with PointNet which cannot be converted to ONNX in a simple way. When I use the saved_model format from TF,

```
std::wstring model_path(L"C:/Path/saved_model.pb");
```
I get the error:
```
ERROR: Error reading file: C:/Path/saved_model.pb
rmlLoadModel failed: Error reading file: C:/Path/saved_model.pb
```

How can a model be saved in TF for compatibility?

**Comment by JohnBravo08am** [comment]
Hello, @cjtrueeb , have you checked your model with TF, is it correctly loaded? Could you please also attach the model you have?

**Comment by achernigin1987** [comment]
We don't support "saved_model" format. Only original frozen models for TF 1.x
