### ISSUE TITLE
Include sample makefiles, supported models and sample inputs..

### ISSUE THREAD

**Issue by oscarbg** [GPUOpen-LibrariesAndSDKs/RadeonML#2]
Hi,
suggesting some improvements to RadeonML..
would be nice to have included makefiles or a build script for support OSes on samples folder ..
even a simple one like I solved on Ubuntu with something like:
```
gcc graph_ops.c -I ../include ../Ubuntu18/libRadeonML.so -o graph_ops
gcc load_model.c -I ../include ../Ubuntu18/libRadeonML.so -o load_model
g++ graph_ops.cpp -I ../include ../Ubuntu18/libRadeonML.so -o graph_ops.cxx
g++ load_model.cpp -I ../include ../Ubuntu18/libRadeonML.so -o load_model.cxx
```
next samples fail to run due to searching for inexistant models:

 ./graph_ops
```
INFO: MIOpen version: 2.0.1
ERROR: Model file not found: path/model.pb
Model file not found: path/model.pb
```
so I copy from models path any model like upscale2x_fast.pb to path/model.pb ..
now it failts to run due to "Unsupported GPU operation: Clip" ..
can you include models that doesn't require unsupported features? or Clip operation is supported on other OSes?

./graph_ops
```
INFO: MIOpen version: 2.0.1
ERROR: Cannot create RMLGraph_0x564be7335aa0/clip:Clip: Unsupported GPU operation: Clip
Cannot create RMLGraph_0x564be7335aa0/clip:Clip: Unsupported GPU operation: Clip

```
similarly load_model wants a onnx file which is missing..

./load_model
```
INFO: MIOpen version: 2.0.1
ERROR: Model file not found: model/path.onnx
Model file not found: model/path.onnx
```

lastly graph_ops searchs for
    "path/color.bin",
        "path/albedo.bin",
        "path/depth.bin",
        "path/normal.bin",
which are also missing.. would be nice to include it also for easy testing..

Note I understand this is for developers but easier steps to having working the included samples would be nice..

thanks..

**Comment by oscarbg** [comment]
EDIT: testing a resnet50-v2-7.onnx fails with:
./load_model
```
INFO: MIOpen version: 2.0.1
ERROR: Cannot create resnetv24_batchnorm0_fwd:BatchNorm: Unsupported GPU operation: BatchNorm
Cannot create resnetv24_batchnorm0_fwd:BatchNorm: Unsupported GPU operation: BatchNorm

```

**Comment by JohnBravo08am** [comment]
Hi, @oscarbg, MIOpen backend doesnt' support Clip and BatchNormalization operations for now. There is an information regarding operations support in RadeonML_graph.h file. You can try DirectML backend as it supports most of the operations.

As for graph_ops sample you can only run it with denoiser model (denoise_c9_ldr.pb), as it states in the description of the sample:
```
/*
 * This sample demonstrates how ldr-denosier could be converted to hdr-denoiser
 * using tone-mapping as preprocessing and gamma-correction as postprocessing
 */
```

**Comment by JohnBravo08am** [comment]
As for the input files, you can generate them if you have 9-channel image. You can try the files in the attach for the model I mentioned above (denoise_c9_ldr.pb).
[inputs.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonML/files/4700977/inputs.zip)

**Comment by BenjaminCoquelle** [comment]
a cmake has been pushed in the repo for building

**Comment by oscarbg** [comment]
thanks for fast responses,

@JohnBravo08am thanks for all info.. guess I didn't spend much time reading documentation.. :-)
tested on DirectML with your attached inputs and have working sample.. perhaps inputs could be added to project for simple evaluation of project: i.e. compile & run sample scenarios..

@BenjaminCoquelle thanks for adding CMake support..

guess I can close now since issues are now solved..

**Comment by shrutiramesh1988** [comment]
Could you please let me know how to run the 2 samples included as part of RadeonML?

I'm unable to run inference with load_model.c. Tried with the denoise.pb file.
**const rml_char* model_path = "models/denoise_c3_hdr.pb";**
gcc  samples/load_model.c -I include/ -L Ubuntu18/ -lRadeonML-MIOpen -lMIOpen -o load_model
./load_model
INFO: MIOpen version: 2.0.1

It only prints this much. A ReadMe on how to run the samples (how many inputs to pass etc) would be really useful. I'm struggling to run the 2 samples.

As suggested above, I also tried running graph_ops sample with denoise_c9_ldr.pb by downloading the 4 bin files from inputs.zip and placing them under path.

g++  samples/graph_ops.cpp -I include/ -L Ubuntu18/ -lRadeonML-MIOpen -lMIOpen -o graph_ops_sample

ls path/
albedo.bin  color.bin  depth.bin  model.pb  normal.bin

./graph_ops_sample
INFO: MIOpen version: 2.0.1
ERROR: Cannot create RMLGraph_0x55e014cd4e60/clip:Clip: Unsupported GPU operation: Clip
rmlCreateModelFromGraph failed: Cannot create RMLGraph_0x55e014cd4e60/clip:Clip: Unsupported GPU operation: Clip

Any help appreciated. Thanks

**Comment by shrutiramesh1988** [comment]
We are trying this on Ubuntu 18.04 machine, not Windows

**Comment by JohnBravo08am** [comment]
@oscarbg , thank you for the feedback, we'll update samples documentation.

Hi, @shrutiramesh1988 , _graph_ops_ sample will work only with DirectML backend for now, we'll make it work with MIOpen too in the future updates. As for the _load_model_ sample, this is just basic example of how to load and inference model (using stub data), it doesn't produce any output. Probably, it's good idea to extend this sample to inference different models using real data, thank you for the feedback.

**Comment by JohnBravo08am** [comment]
@shrutiramesh1988 you can raise a new issue to track progress, if you want.
