### ISSUE TITLE
Transpose error

### ISSUE THREAD

**Issue by Armin234** [GPUOpen-LibrariesAndSDKs/RadeonML#7]
Hi,
with my own Onnx model I get the error 
"Error parsing Transpose_0001 (Transpose): Layout with axes permutation 0, 2, 1, 3 is not supported"

Is there a workaround ?

**Comment by JohnBravo08am** [comment]
Hello, @Armin234 , it seems like desired layout for these axes was NWHC, which is unsupported. We support NHWC or NCHW layout for rank 4 tensors.

**Comment by Armin234** [comment]
Hi John,
after changing the transpose i get the following error " Error parsing 88Slice_2 (Slice): Operation not found: 8Transpose. Ensure the graph is valid and topologically sorted"
![Unbenannt](https://user-images.githubusercontent.com/37782776/85129082-d03d2b00-b232-11ea-9f6a-6f93cf22ca88.PNG)

**Comment by JohnBravo08am** [comment]
@Armin234 , can you check if Slice node input has the same name as Transpose node name?

**Comment by Armin234** [comment]
After replacing translate with reshape, I get the error " Unsupported attribute type: 4", but consulting RadeonML_graph.h I couldn't identifiy the unsupported operation.

![armin_1_1 onnx](https://user-images.githubusercontent.com/37782776/85130882-092acf00-b236-11ea-9fc0-aa251574fe1a.png)

**Comment by Armin234** [comment]
the slice node is named 8slice_2 and the translate node is named 8Transpose, as you can see in the image

**Comment by JohnBravo08am** [comment]
Could you please upload this model? See my answer for "Unsupported attribute type: 4": https://github.com/GPUOpen-LibrariesAndSDKs/RadeonML/issues/6#issuecomment-646604323

**Comment by Armin234** [comment]
The model is to big for upload, so I have it uploaded to wetransfer

https://we.tl/t-8B0GPfXyX7

**Comment by JohnBravo08am** [comment]
Thanks, I've checked Transpose.onnx model, the main issue here:
**Transpose** node name is **Transpose_0001**
**Slice** node input name is **8Transpose**
So, we simply coudn't find such node in graph. Suggestion - rename Transpose node to 8Transpose.
This is a general rule for all operations - node input name must match corresponding node name.

**Comment by Armin234** [comment]
I didn't not know where the node name Transpose_001 is coming from. This name ist generated automatically from the "Sony neuronal network Console" when I make the esport to onnx.  But the Ouput from the Transpose layer is named correctly, perchaps looking for a layer with the corresponding output name could be more comfortable for the user

![Unbenannt](https://user-images.githubusercontent.com/37782776/85133686-75f49800-b23b-11ea-96ef-d4ec1236823d.PNG)

**Comment by JohnBravo08am** [comment]
Probably, yes, but almost every onnx of tf model follows this rule. Quick workaround here is to edit onnx model by changing Transpose node name.

**Comment by Armin234** [comment]
Okay, I will try to edit the onnx model

**Comment by achernigin1987** [comment]
Fixed in the 0.9.7
