### ISSUE TITLE
Performance compared to WinML?

### ISSUE THREAD

**Issue by artths** [GPUOpen-LibrariesAndSDKs/RadeonML#9]
Could you please point out the performance of RadeonML compared to WinML? We have our model running very slow on WinML compared to hlsl implementation. Can RadeonML boost it?

**Comment by BenjaminCoquelle** [comment]
The performance will likely be the same as like winML we use DIrectML as a back end.
Can you maybe give more info about your model?
Convolution size, tensor layout etc...
What driver and card do you use?

**Comment by artths** [comment]
I was trying to run ESPCN. I have Nvidia 2070 and latest drivers.
Just seems to me WinML adds a lot of overhead, so hlsl is much faster.
I believe using DirectML should be faster but it's hard enough to use.

**Comment by BenjaminCoquelle** [comment]
Well I can't comment on otpmization put in place by nvidia for DirectML
Note that RadeonML like winML uses DirectML as a backend on windows

**Comment by artths** [comment]
Thank you for the answers.
